development:
  adapter: postgresql
  encoding: unicode
  database: store_development
  pool: 5
  timeout: 5000
  username: lo
  password: lorenzo
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  timeout: 5000
  username: lo
  password: lorenzo
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: store_test
  pool: 5
  timeout: 5000
  username: lo
  password: lorenzo
  host: localhost